### ISSUE TITLE
The “Auto scale Y axis” setting is reset when clicking the “back” button

### ISSUE THREAD

**Issue by Arkanosis** [binjr/binjr#108]
That's a topic for you @fthevenet: the back button doesn't work :)

https://user-images.githubusercontent.com/124583/111760437-ffa2c600-889e-11eb-8b95-2ddc7e960e11.mp4

**Comment by fthevenet** [comment]
Thanks to your video capture; it is pretty clear what's actually going on here.

What's actually happening is not really that pressing *back* resets the Y scale; in fact it does, but that's on purpose; going back and forth in the navigation history is meant to restore both the X *and* Y coordinates.

The issue here is that changing the Y scale through the "Chart properties" panel does *not* create a checkpoint in the navigation history, so when you move forward and then press back you're returned to the last saved checkpoint, which is *before* you changed the Y scale (which is obviously not the expected behaviour, and a bug).
