### ISSUE TITLE
The test demo doesn't work

### ISSUE THREAD

**Issue by raven2cz** [binjr/binjr#110]
I tried to test the demo, but there is exception;
![image](https://user-images.githubusercontent.com/20504243/114931250-85c21600-9e25-11eb-83b4-9ed339848663.png)

**Comment by fthevenet** [comment]
Hi,

Thanks for reporting that.
Indeed, I haven't updated the demo adapter to the new, incompatible, binjr v3 API, hence the crash.
I'll try to do that soon.

**Comment by fthevenet** [comment]
I have now publish a new release of the plugin that works with the latest version of binjr (v3+).
You can download it from: https://github.com/binjr/binjr-adapter-demo/releases/latest

*⚠ Please make sure that you remove the old version of the demo plugin from the `plugins` folder (not just rename it) otherwise it will conflict with the new version.*

Feel free to reopen this issue if you're still having problems using the demo plugin.
