### ISSUE TITLE
how to read file with time in seconds

### ISSUE THREAD

**Issue by uselessgames** [binjr/binjr#148]
Hello - I am trying to read a file with just seconds in the time col. sample below:

I created a parsing profile, sample also below, I import then when I go to graph get the following error `invalid value of secondOfMinute`

it seems to try to read seconds from-to 0-59, but my file is elapsed seconds. so i tried just the default seconds since epoch, it's not actually seconds since epoch but I dont care just need to plot. but when i plot it returns other errors in the chart source where it says nan in all columns (min, max, etc. )

any ideas how to plot? 
cheers

sample file
```
time, a, b, c, d, e, f
5, -8721, -106329, -37357, 139730, 53306, -42463
15, -8731, -106354, -37387, 139748, 53304, -42438
25, -8755, -106356, -37403, 139757, 53347, -42419
36, -8765, -106367, -37357, 139794, 53354, -42397
46, -8785, -106398, -37294, 139775, 53337, -42420
56, -8819, -106376, -37296, 139771, 53349, -42445
66, -8808, -106419, -37243, 139774, 53353, -42457
76, -8836, -106400, -37159, 139741, 53343, -42428
87, -8823, -106380, -37171, 139781, 53327, -42482
97, -8830, -106412, -37160, 139763, 53311, -42476
107, -8871, -106377, -37096, 139782, 53356, -42504
118, -8860, -106372, -37084, 139769, 53373, -42460
127, -8897, -106353, -37052, 139771, 53380, -42359
138, -8893, -106347, -36980, 139743, 53361, -42400
148, -8921, -106326, -36982, 139731, 53402, -42389
158, -8899, -106339, -36977, 139696, 53429, -42381
168, -8918, -106291, -36984, 139670, 53454, -42490
178, -8908, -106269, -36943, 139663, 53440, -42459
189, -8930, -106261, -36950, 139638, 53462, -42343
...
```

parsing profile
```
[{"delimiter":",","quoteCharacter":"\"","timestampColumn":0,"excludedColumns":[],"readColumnNames":true,"formattingLocale":"en-US","captureGroups":{"SECOND":".*"},"lineTemplateExpression":"$SECOND","profileName":"New profile","profileId":"7acbd955-6dde-4a93-8e3d-de22ebc68afa","regex":"(?\u003cSECOND\u003e.*)"}]
```

**Comment by fthevenet** [comment]
Hi,

Yes the `SECOND` token is meant to represent the the number of seconds a time stamp, not a duration, and cannot therefor be larger than 59.
As you figured out yourself, using the the `EPOCH` token is the right way to plot that data while keeping the correct elapsed time between 2 samples, even though the date and times themselves will be meaningless.

Now, the reason the numeric values in the other columns are not recognized is totally unrelated: this is due to the space preceding each number, right after the comma. The parser does not trim those and therefore considers the value is not a number.

Arguably, CSV files should not contain extraneous spaces, but the it is the curse of the so-called "format" to be so loosely defined -- and for what little is defined to be routinely abused -- that I suspect your case is far from uncommon.
So I'll consider adding an option to trim cell values before attempting to parse them as numbers.

**Comment by uselessgames** [comment]
i didnt even notice the extra space... thank you, all is well now.

**Comment by fthevenet** [comment]
In any case, I've added an option to trim the cells, on a per profile basis.
That was trivial enough and, as I said, quite possibly a fairly frequent problem.
Should be available in the next release.
