### ISSUE TITLE
Feature request: use 5 secondary ticks instead of 4, per a major (grid) tick

### ISSUE THREAD

**Issue by xrysf03** [binjr/binjr#152]
First things first: thanks for Binjr - my favourite time series explorer :-)

I have a minor cosmetic feature request:

In time series charts, the scale along the Y axis seems to favour "decimal rounded" spacing of the major ticks (grid lines). Whole units, tens, hundreds, you get the idea. Or sometimes "five" of the decade.
Each "cell" of this major spacing is further sub-divided by 2nd-order or minor ticks.
In its current shape and form, Binjr uses strictly 4 minor "bins" per a major tick, delimited by 3 minor tick marks.
Thus, if the major tick is 10, the minor bin is 2.5.
If the major tick is 50, the minor bin is 12.5.

I find it slightly difficult to read.
I would appreciate very much, if there were *5* minor bins, instead of four. I.e., 4 minor tick marks per major grid unit.
Thus, if the major tick spacing is 10, the minor bin is 2.
For a major tick spacing of 5, you get the minor bin = 1.
To my visual cortex, this "decimal-aligned" subdivision feels more digestible :-)

There should be a screenshot somewhere around there...
![binjr_tmp](https://github.com/user-attachments/assets/c314cdd1-f084-4edd-a30f-92abb73812c2)
Thanks for your attention :-)

**Comment by fthevenet** [comment]
Hi!

I have to admit that over my 7+ years staring at graphs in binjr, I had never really paid attention to that... But now that you mention it, I just cannot unsee it! 😅

The choice of 3 minor ticks per major ticks if entirely arbitrary, but if I had to guess, it was chosen (it is some third party code that I reused) to be a good compromise so that the axis remains readable as the screen real estate between two major ticks is reduced (e.g. keep in mind that the axis is redrawn and ticks are rearranged as the app window is resized and the number of charts per screen increased):

![image](https://github.com/user-attachments/assets/02f712d9-760d-4ada-8fa9-20eac66b9e41)


But after giving this more thoughts, I think a more elegant way to handle this is to reduce the number of minor ticks (in this case to just one) as the physical space in between them gets too small. i.e.:

![image](https://github.com/user-attachments/assets/31eb51dd-2f12-4a45-9df5-a5376a3b93a0)

**Comment by fthevenet** [comment]
I'll prepare a preview build that implements the adaptive behaviour illustrated above, and also expose parameters such as the preferred number of minor ticks and the threshold at which it is reduced to one as user settable values, so that it is possible to recreate the old behaviour in case someone really misses it.

Would you be inclined to give it a try and provide some feedback once it is ready?

**Comment by fthevenet** [comment]
Oh... 🤦 
I just realized that while it makes all the sense in the world to subdivide in five bins when working with a decimal scale, the same isn't true when you work with powers of 2 —which has become such a deeply ingrained habit that this probably explain why this issue had never bothered me before...
For instance, when you subdivide 1 KiB (KibiByte), you'll to be more interested in a half (512), a quarter (256), an eighth (128), than 1.2, 1.4, 1.6, etc... in which case the original behaviour makes a lot of sense.

This means that the ideal number of minor ticks should be different for graphs using binary units than the ones using metric/decimal.

![image](https://github.com/user-attachments/assets/8c4b65c5-9415-43fe-919d-74264a870cb9)

**Comment by fthevenet** [comment]
There is now a preview build that you can try here: https://github.com/binjr/binjr/releases/tag/v3.20.0-SNAPSHOT

The various parameters that affects this can be adjusted: go to the debug console (press F12), go to the "Preferences" tab and filter out on the word "tick":

![image](https://github.com/user-attachments/assets/4fbb67bf-23fb-46ed-8648-f68f3d6ac54e)

**Comment by fthevenet** [comment]
Fixed in 0069e3aceec12f34a38b80281125a6ad3973da9f

**Comment by xrysf03** [comment]
Apologies for not returning sooner. Respect for your swift response time. 
Testing the feature now in 3.20.0, the upload from two days ago.
The new logic does seem to produce good results for minor ticks.
At some vertical scales, it looks beautiful, initially I went YAY!
The verbatim subject of this ticket has certainly been addressed.

Apologies for nitpicking further: at other scales, I can see that the *major* vertical tick spacing is ... ahem ... slightly irritating to my eye, the same way minor ticks used to be (and are not any more). Just food for thought - if the major ticks could use some re-silvering too. 

Also, while I'm at this, and creeping the scope even further, note how the spacing of the horizontal grid is nicely rounded to a meaningful unit / multiple / order, but... could you make the tick *positions* rounded+aligned to that same "time chunk"? I understand that in that case, the grid would not start with a whole time quantum on the left - not sure how much this is a problem in your source code structure.

I will include some screenshots, good and not so good.

In the following screenshot, note how the logic has wisely chosen a minor spacing of 2 minors per major, but the major ticks themselves are not "nice decimal numbers" = sticking to the binary division that you were talking about. Thus, a major tick is 250, and the minor tick ends up being 125... 

![01_major_ticks_less_than_perfect](https://github.com/user-attachments/assets/52b7ee82-8f4b-434b-97dd-1dd2d55c7848)

Would you consider re-thinking the algorithm a little? How about this:
1. settle on a reasonable minor spacing
2. settle on a reasonable multiple of the minor spacing, to form the major spacing step, which at the same time will be a nice number at the major scale... 

I know that this is non-trivial, "nice" is a matter of taste, may be difficult to algorithmize. Different people for different data may prefer binary or decadic division. (Logarithmic scale anyone?) Maybe let the user choose between binary and decadic. For a decadic division, how about this: for the minor unit, pick the lowest reasonable multiple of [1 | 2 | 5 ], times a nearby decadic order. For the major tick, use a convenient multiple of the minor tick - a multiple of [ 2 | 5 ] that combines into one of [ 1 |  2 | 5 ] at its decadic order. As plausible combinations, let me suggest "minor=1 by 5" or "minor=2 by 5" or still "minor=5 by 2", but perhaps not "minor=5 by 5". Yes I am nuts...

In the following screenshot, pay attention to two aspects:
1) the minor ticks are spaced 5 minors per major, and the minor tick corresponds to 50, which is good. So it's not very irritating, that the major spacing is "not neatly decadic" 250 - which neatly combines into 1000.
2) also note the horizontal tick alignment. The *equidistant spacing step* is nice, but the ticks are not aligned to nice numbers on the actual scale (off by a fraction).

![02_minor_ticks_save_the_show__horizontal_tick_positions_not_rounded](https://github.com/user-attachments/assets/60c20740-4fca-441e-a9fd-6d3853e24b9c)

In the following screenshot, note how neatly decimal the scale is.

![03_this_makes_sense](https://github.com/user-attachments/assets/8f9e9e50-36b7-4b3d-91e7-d86d5257ae80)

**Comment by fthevenet** [comment]
The algorithm that picks the value for major ticks is tuned so as to try and keep the spacing between ticks more of less constant, in terms of screen real-estate, as the pane for chart grows or shrinks.
To do that and still retain value that are not completely arbitrary, it takes a parameter a list of numbers that it will attempt to divide the current height of the chart by, and settle on the value closest to its target.
Up until now, these parameters could not be set by end users, but I've exposed then in the latest preview build (be sure to re-download it if your version is older that yesterday), albeit in the "debug console" and not the main settings panel.

In order to access it, you have to press F12, and select the "Preference" tab. Then you can filter on the word "tick" to narrow down the number of options.
The one you're interested in is called `decimalAxisTickDividers`; the default for this is `[1.0, 2.5, 5.0]`.
If you would like to skew the algorithm's behavior so that it favors settling on decimal multiples instead of maintaining the regularity of the grid, then you could try and change this value to `[1.0]` (like in the screenshot below) 

![image](https://github.com/user-attachments/assets/7ed2da1e-7bd0-4481-bc0f-29ac8bb4feb6)

**Comment by xrysf03** [comment]
Excellent, thanks for those tunable parameters :-)
I've tried decimalAxisTickDividers = [1.0,2.0,5.0] which already looked better to me, but still yielded some marginally unpleasant combinations (a corner case where major tick was say 500, and got split into 2 minors = 250 per minor) - anyway already pretty good.
I then tried decimalAxisTickDividers = [1.0,2.0] which avoids the occurrence of 250 (quarters) altogether, at the cost of sometimes having the major grid lines rather sparse (because the five-ish multiple is missing).
Anyway - I can now fiddle with this ad hoc if I ever get the nerve :-) and I'm happy the way it is.

If you ever get to the rounded alignment of the time axis ticks, that would be nice, but really more like a cherry on the already beautiful cake. I mean this isn't something I would keep as a complaint. Thank you for your hard work :-)

**Comment by fthevenet** [comment]
Glad you find it useful.

The time axis' implementation uses a different logic to determine the values for the ticks. It is also more complex has the value types displayed change to adapt to the time range being shown; as you zoom out if goes from millisecond time stamps to minutes, hours, days, month, years, etc....
That's not to say it wouldn't feasible to address to points you raised, but that'd be a whole new investigation. Maybe one day... ¯\\\_(ツ)_/¯
